server:
  global:
    scrape_interval:     15s # By default, scrape targets every 15 seconds.
    evaluation_interval: 15s # By default, scrape targets every 15 seconds.
    # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'pyapp'

extraScrapeConfigs: |
  - job_name: pyapp
    scrape_interval: 5s
    static_configs:
    - targets:
      - prometheus-statsd-exporter.prometheus-statsd-exporter.svc.cluster.local:9102



     