apiVersion: v1
kind: ConfigMap
metadata:
  name: pyapp
data:
  dbhost: {{ .Values.dbConf.host }}
  dbuser: {{ .Values.dbConf.user }}
  dbport: {{ .Values.dbConf.port | quote }}
  dbname: {{ .Values.dbConf.name }}
  statsdhost: {{ .Values.statsdConf.host }}
