apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pyapp.fullname" . }}
  labels:
    {{- include "pyapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pyapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pyapp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /dbhealth
              port: http
            initialDelaySeconds: 6
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pyapp
                  key: dbpass
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: pyapp
                  key: dbuser
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: pyapp
                  key: dbhost
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: pyapp
                  key: dbname
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: pyapp
                  key: dbport
            - name: STATSD_HOST
              valueFrom:
                configMapKeyRef:
                  name: pyapp
                  key: statsdhost                    
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
