apiVersion: v1
kind: Service
metadata:
  name: {{ include "pyapp.fullname" . }}
  labels:
    {{- include "pyapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: 31001
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "pyapp.selectorLabels" . | nindent 4 }}
